apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: docker-devfile-sample-hello-world-zhfd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: docker-devfile-sample-hello-world-zhfd
    app.kubernetes.io/part-of: test-app-fhzq
  name: docker-devfile-sample-hello-world-zhfd
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: docker-devfile-sample-hello-world-zhfd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: docker-devfile-sample-hello-world-zhfd
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-hegu-tenant/test-app-fhzq/docker-devfile-sample-hello-world-zhfd@sha256:b0d87b4e0330cf4f3bb763efe1a1373041bbceeb41ccc69a78e74e10a800832a
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
